version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_java_book
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-network

  redis:
    image: redis:7.2
    container_name: redis_java_book
    restart: always
    ports:
      - "6379:6379"
    networks:
      - spring-network

  libreria:
    build: ./Libreria-Java-Book
    container_name: libreria_java_book
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_DB=${SPRING_DATASOURCE_DB}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - spring-network

volumes:
  postgres_data:

networks:
  spring-network:
    driver: bridge